construccion_thompson: construcciones_thompson.cpp regex.txt
	clear
	g++ -std=c++14 construcciones_thompson.cpp -o construcciones_thompson -pedantic-errors -Wall
	./construcciones_thompson < regex.txt
	rm ./construcciones_thompson
