subconjuntos : subconjuntos.cpp
	clear
	g++ -std=c++14 subconjuntos.cpp -o subconjuntos
	./subconjuntos
	rm ./subconjuntos
	dot -Tsvg entrada.dot > entrada.svg
	dot -Tsvg salida.dot > salida.svg
	rm entrada.dot
	rm salida.dot